{{
    config(
        materialized="table",
        alias="customer",
        schema="public"
    )
}}

WITH CTE1 AS
(
SELECT C.ID AS CUSTOMER_ID, 
C.FIRST_NAME AS FIRST_NAME,
C.LAST_NAME AS LAST_NAME,
FIRST_VALUE(O.ORDER_DATE) OVER (PARTITION BY C.ID ORDER BY O.ORDER_DATE ASC) AS FIRST_ORDER,
LAST_VALUE(O.ORDER_DATE) OVER (PARTITION BY C.ID ORDER BY O.ORDER_DATE ASC) AS LAST_ORDER,
FROM
{{ source('hevo_project','SNOW_RAW_PS_RAW_CUSTOMERS') }} C 
INNER JOIN {{ source('hevo_project','SNOW_RAW_PS_RAW_ORDERS') }} O
ON
C.ID=O.USER_ID
INNER JOIN {{ source('hevo_project','SNOW_RAW_PS_RAW_PAYMENTS') }} P
ON O.ID=P.ORDER_ID),
CTE2 AS
(
SELECT O.USER_ID AS USER_ID,
COUNT(O.ID) AS NUMBER_OF_ORDERS,
SUM(P.AMOUNT) AS CUSTOMER_LIFETIME_VALUE
FROM
{{ source('hevo_project','SNOW_RAW_PS_RAW_ORDERS') }} O
INNER JOIN {{ source('hevo_project','SNOW_RAW_PS_RAW_PAYMENTS') }} P
ON O.ID=P.ORDER_ID
GROUP BY 1)

SELECT CTE1.CUSTOMER_ID,CTE1.FIRST_NAME,CTE1.LAST_NAME,CTE1.FIRST_ORDER,CTE1.LAST_ORDER,
CTE2.NUMBER_OF_ORDERS,CTE2.CUSTOMER_LIFETIME_VALUE
FROM CTE1 JOIN CTE2 
ON CTE1.CUSTOMER_ID=CTE2.USER_ID