version: 2

sources:
  - name: hevo_project 
    database: PC_HEVODATA_DB
    schema: public
    tables:
      - name: SNOW_RAW_PS_RAW_CUSTOMERS
        columns:
          - name: ID
            tests:
              - unique
              - not_null
              
                
      - name: SNOW_RAW_PS_RAW_ORDERS
        columns:
          - name: ID
            tests:
              - unique:
              - not_null:
                  
      - name: SNOW_RAW_PS_RAW_PAYMENTS
        columns:
          - name: ID
            tests:
              - unique:
              - not_null:
                  
       