version: 2

sources:
  - name: hevo_project 
    database: PC_HEVODATA_DB
    schema: public
    tables:
      - name: SNOW_RAW_PS_RAW_CUSTOMERS
        columns:
          - name: id
            tests:
              - not_null
              - unique
                  

      - name: SNOW_RAW_PS_RAW_ORDERS
        columns:
          - name: id
            tests:
              - not_null
              - unique
              
      
      - name: SNOW_RAW_PS_RAW_PAYMENTS
        columns:
          - name: id
            tests:
              - not_null
              - unique
              

                  
       